### ISSUE TITLE
A different style to access properties

### ISSUE THREAD

**Issue by ronkorving** [Wizcorp/domes#2]
It can be a bit confusing when the path is a string, but arguments are as well.

Given a dome:

``` js
var d = dome({ list: [] });
```

I would like to replace this:

``` js
d.push('list', 'item1', 'item2');
```

With this:

``` js
d.at('list', function (d) {
    d.push('item1', 'item2');
});
```

Or with arrow functions:

``` js
d.at('list', d => d.push('item1', 'item2'));
```

Of course both the current style and this new style can co-exist, at least for a while.

**Comment by AlmirKadric** [comment]
yeah this is where sub-objects would be nice
I personally would prefer the following as it is more explicit and cleaner (subjective)

```
d.wrap('list').push('item1', 'item2')
```

**Comment by ronkorving** [comment]
The reason why I was suggestion function passing style is that would allow multiple operations at a single location. That would avoid the need for parsing the path multiple times when you don't need it to. Does that make sense? The chaining approach you suggest may promote an anti-pattern, no different from what jQuery does with its `$('.foo')` being so nice and easy to write and repeat, but at a real price.

**Comment by kefniark** [comment]
Copy pasta from hipchat:

> I agree that the current push() function is quite confusing.
> 
> Both of your approach make sense. Almir's one is probably easier to read but seems a bit too magic and hide maybe too much operation (the analogy to jQuery seems really true).
> 
> If I have to choose, I would probably go with a sub-function: `d.at('list', d => d.push('item1', 'item2'));`

**Comment by nullorvoid** [comment]
```
d.at('list', d => d.push('item1', 'item2'));
```

Can this be used as such

```
d.at('list', list => {
  if (list < 20) {
    for loop {
        list.push('item' + i);
    }
  }
});
```

?

**Comment by ronkorving** [comment]
I have a branch ready (not yet pushed), where that would look like this:

``` js
d.mutate('my.obj.foo.list', m => {
  var i = 0;
  while (m.get().length < 20) {
    m.push('item ' + i++);
  }
});
```

Read `m` as "mutator". We want to know what changes when, so you don't want to mutate the array directly. You want to go through the mutator proxy to do so, hence this approach. I could add a `length` helper though to make the example above a bit shorter. All other array mutating methods are already there anyway, so I might as well add a `length` getter.

**Comment by nullorvoid** [comment]
so with Almirs code it would look something like

d.wrap('list').mutate(function());

?

Edit: Just initial impressions, as I've mostly always used the => in c# this idea of passing in a parameter to a function is not uncommon, so I would use this, however the get? wrap function I also don't mind because its explicit, although I wouldnt have gone with 'wrap'.

**Comment by ronkorving** [comment]
It would be:

``` js
var i = 0;
while (d.read('my.obj.foo.list').get().length < 20) {
  d.mutate('my.obj.foo.list').push('item ' + i++);
}
```

But I would rather let @AlmirKadric answer that, because he may see a more elegant variation.

**Comment by ronkorving** [comment]
In an upcoming PR, I (almost accidentally) support both.

``` js
var m = d.mutate('my.obj.foo.list');
for (var i = 0; m.length < 20; i++) {
  m.push('item ' + i);
}
```

``` js
d.mutate('my.obj.foo.list', function (m) {
  for (var i = 0; m.length < 20; i++) {
    m.push('item ' + i);
  }
});
```

and yes, even (but please don't...):

``` js
for (var i = 0; d.read('my.obj.foo.list').length < 20; i++) {
  d.mutate('my.obj.foo.list').push('item ' + i);
}
```

**Comment by ronkorving** [comment]
@nullorvoid I also wouldn't have gone with wrap. Wrap is already an existing API in this module and doesn't do what this does :) I explicitly named them `read` and `mutate`. The reason for having 2 proxy creators like this is that a reader on a property chain doesn't create those properties along the way if they're missing. A mutator will. A cool side-effect is that you could use this differentiation to give read/write access based on whatever you want. It's a very nice safety net when you're writing code that whatever happens in a particular block is read-only and cannot generate any side-effects on your data.
